version: '3'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:0.10.0-alpine
    restart: always
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  acme-companion:
    image: nginxproxy/acme-companion:2.0.2
    restart: always
    container_name: acme-companion
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - DEFAULT_EMAIL=mstefanutti24@gmail.com

  mstefa:
    build: .
    restart: always
    expose:
      - "80"
    volumes:
      - ./:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=mstefanutti.com,www.mstefanutti.com
      - LETSENCRYPT_HOST=mstefanutti.com,www.mstefanutti.com
      - LETSENCRYPT_EMAIL=mstefanutti24@gmail.com
    depends_on:
      - nginx-proxy
      - acme-companion
      
volumes:
  conf:
  vhost:
  html:
  dhparam:
  certs:
  acme: